spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  batch:
    initialize-schema: always 
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /swagger*
  resources:
    add-mappings: false
  datasource:
    url: jdbc:h2:mem:farmacia
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  rabbitmq:    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchange:
        producer: ex.producer.farmacia
      routing-key:
        producer: rk.producer.farmacia
      dead-letter:
        producer: dl.producer.farmacia  
server:
  port: 8082